
[splunktcp://9997]
disabled = 0
connection_host = dns

[monitor:///var/log/apache2/access.log]
disabled = 0
index = main
sourcetype = access_combined
host = dvwa_target_machine
_TCP_ROUTING = *

[monitor:///var/log/apache2/error.log]
disabled = 0
index = main
sourcetype = apache_error
host = dvwa_target_machine

[monitor:///var/log/auth.log]
disabled = 0
index = main
sourcetype = linux_secure
host = dvwa_target_machine